name: 'Build Staging App and Deploy to Server'

on: 
  push:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy Staging App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: Build client and zip server files
        env:
          MONGO_USER: ${{ secrets.STAGING_MONGO_USER }}
          MONGO_PASS: ${{ secrets.STAGING_MONGO_PASS }}
          DROPBOX_TOKEN: ${{ secrets.STAGING_DROPBOX_TOKEN }}
          TRUSTED: ${{ secrets.TRUSTED }}
          G_CLIENT_ID: ${{ secrets.G_CLIENT_ID }}
          G_CLIENT_SECRET: ${{ secrets.G_CLIENT_SECRET }}
          CALENDAR_ID: ${{ secrets.STAGING_CALENDAR_ID }}
          CALENDAR_URL: ${{ secrets.STAGING_CALENDAR_URL }}
        run: |
          npm install -g yarn
          cd $GITHUB_WORKSPACE && ls -la
          cd client
          echo "{\"backend\":\"https://dev.tams.club\"}" >| src/files/config.json
          yarn install && yarn build
          cd build
          zip -r ../../tams-club-cal-client.zip .
          cd ../../server
          echo "MONGO_USER=$MONGO_USER" >| .env
          echo "MONGO_PASS=$MONGO_PASS" >> .env
          echo "MONGO_URL=tams-cal-db-staging.7d0nz.mongodb.net" >> .env
          echo "DROPBOX_TOKEN=$DROPBOX_TOKEN" >> .env
          echo "PORT=8082" >> .env
          echo "TRUSTED=$TRUSTED" >> .env
          echo "G_CLIENT_ID=$G_CLIENT_ID" >> .env
          echo "G_CLIENT_SECRET=$G_CLIENT_SECRET" >> .env
          echo "CALENDAR_ID=$CALENDAR_ID" >> .env
          echo "CALENDAR_URL=$CALENDAR_URL" >> .env
          mv staging.ecosystem.config.js ecosystem.config.js
          yarn install
          zip -r ../tams-club-cal-server.zip .
          cd ..
        
      - name: Deploy to Droplet with scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          source: 'tams-club-cal-client.zip,tams-club-cal-server.zip'
          target: '/var/www'
      
      - name: Unzip Files on Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www
            rm -rf tams-club-cal-staging-client/{*,.*}
            rm -rf tams-club-cal-staging-server/{*,.*}
            unzip tams-club-cal-client.zip -d tams-club-cal-staging-client
            unzip tams-club-cal-server.zip -d tams-club-cal-staging-server
            rm tams-club-cal-client.zip
            rm tams-club-cal-server.zip
